service: ringcentral-bugsnag-notification-app
frameworkVersion: '3'
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment: ${file(./env.yml)}
  profile: default
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: ""
  deploymentBucket:
    tags:
      Department: dev
      Owner: Your name
      Stage: production
      Environment: your-env-tag
      Team: your-team
      Name: ringcentral-bugsnag-notification-app
  tags:
    Department: dev
    Owner: Your name
    Stage: production
    Environment: your-env-tag
    Team: your-team
    Name: ringcentral-bugsnag-notification-app
package:
  excludeDevDependencies: true
  include:
    - '.json'
    - '.js'
    - 'node_modules/**'
functions:
  app:
    timeout: 30
    handler: lambda.app
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: false
resources:
  Resources:
    webhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bugsnag-rc-notification-webhooks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    rcWebhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bugsnag-rc-notification-rcWebhooks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    authTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bugsnag-rc-notification-authTokens
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    botsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bugsnag-rc-notification-bots
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
